-- ============================================================
-- FILE: 05_gold/01_gold_and_pipeline.sql
-- PURPOSE: Gold aggregations + complete Task DAG pipeline
-- ============================================================

USE ROLE DATA_ENG_ROLE;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE GOLD_DB;

-- ─────────────────────────────────────────────────────────────
-- GOLD TABLES
-- ─────────────────────────────────────────────────────────────
USE SCHEMA SALES_MART;

CREATE TABLE IF NOT EXISTS DAILY_SALES_SUMMARY (
    SUMMARY_KEY         NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_DATE_KEY      NUMBER,
    FULL_DATE           DATE,
    REGION_ID           VARCHAR(20),
    SEGMENT             VARCHAR(30),    -- from SCD2 dim at order time
    ORDER_COUNT         NUMBER,
    UNIQUE_CUSTOMERS    NUMBER,
    GROSS_REVENUE       NUMBER(14,2),
    NET_REVENUE         NUMBER(14,2),
    TOTAL_PROFIT        NUMBER(14,2),
    AVG_ORDER_VALUE     NUMBER(10,2),
    PROFIT_MARGIN_PCT   NUMBER(8,4),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORDER_DATE_KEY, REGION_ID);

USE SCHEMA CUSTOMER_MART;

CREATE TABLE IF NOT EXISTS CUSTOMER_360 (
    SK_CUSTOMER         NUMBER,
    CUSTOMER_ID         VARCHAR(50),
    CUSTOMER_NAME       VARCHAR(200),
    EMAIL               VARCHAR(200),
    CURRENT_SEGMENT     VARCHAR(30),
    CURRENT_LOYALTY     VARCHAR(20),
    REGION_ID           VARCHAR(20),
    TOTAL_ORDERS        NUMBER,
    TOTAL_REVENUE       NUMBER(14,2),
    AVG_ORDER_VALUE     NUMBER(10,2),
    DAYS_SINCE_LAST     NUMBER,
    SEGMENT_CHANGES     NUMBER,        -- how many times segment changed (SCD2 version count)
    LOYALTY_CHANGES     NUMBER,        -- loyalty tier change count
    RFM_SCORE           NUMBER,
    CUSTOMER_TIER       VARCHAR(20),
    DW_UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ─────────────────────────────────────────────────────────────
-- GOLD BUILD PROCEDURES
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE PROCEDURE GOLD_DB.SALES_MART.SP_BUILD_DAILY_SUMMARY()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    v_start TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    DELETE FROM GOLD_DB.SALES_MART.DAILY_SALES_SUMMARY
    WHERE ORDER_DATE_KEY >= TRY_TO_NUMBER(TO_CHAR(DATEADD('day',-3,CURRENT_DATE()),'YYYYMMDD'));

    INSERT INTO GOLD_DB.SALES_MART.DAILY_SALES_SUMMARY (
        ORDER_DATE_KEY, FULL_DATE, REGION_ID, SEGMENT,
        ORDER_COUNT, UNIQUE_CUSTOMERS, GROSS_REVENUE, NET_REVENUE,
        TOTAL_PROFIT, AVG_ORDER_VALUE, PROFIT_MARGIN_PCT
    )
    SELECT
        f.ORDER_DATE_KEY,
        d.FULL_DATE,
        s.REGION_ID,
        c.SEGMENT,             -- SCD2 segment at time of order
        COUNT(DISTINCT f.ORDER_ID)         AS ORDER_COUNT,
        COUNT(DISTINCT f.SK_CUSTOMER)      AS UNIQUE_CUSTOMERS,
        SUM(f.TOTAL_AMOUNT)                AS GROSS_REVENUE,
        SUM(f.NET_AMOUNT)                  AS NET_REVENUE,
        SUM(f.PROFIT)                      AS TOTAL_PROFIT,
        AVG(f.TOTAL_AMOUNT)                AS AVG_ORDER_VALUE,
        CASE WHEN SUM(f.NET_AMOUNT)>0
             THEN (SUM(f.PROFIT)/SUM(f.NET_AMOUNT))*100 ELSE 0 END AS PROFIT_MARGIN_PCT
    FROM SILVER_DB.FACTS.FACT_ORDERS f
    JOIN SILVER_DB.DIMENSIONS.DIM_DATE d ON d.DATE_KEY = f.ORDER_DATE_KEY
    LEFT JOIN SILVER_DB.DIMENSIONS.DIM_CUSTOMERS c ON c.SK_CUSTOMER = f.SK_CUSTOMER
    LEFT JOIN SILVER_DB.DIMENSIONS.DIM_STORES s ON s.SK_STORE = f.SK_STORE
    WHERE f.ORDER_DATE_KEY >= TRY_TO_NUMBER(TO_CHAR(DATEADD('day',-3,CURRENT_DATE()),'YYYYMMDD'))
    GROUP BY 1,2,3,4;

    RETURN OBJECT_CONSTRUCT('status','SUCCESS',
        'duration_sec',DATEDIFF('second',:v_start,CURRENT_TIMESTAMP()));
EXCEPTION WHEN OTHER THEN RETURN OBJECT_CONSTRUCT('status','FAILED','error',SQLERRM);
END;
$$;

CREATE OR REPLACE PROCEDURE GOLD_DB.CUSTOMER_MART.SP_BUILD_CUSTOMER_360()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE v_start TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    TRUNCATE TABLE GOLD_DB.CUSTOMER_MART.CUSTOMER_360;

    INSERT INTO GOLD_DB.CUSTOMER_MART.CUSTOMER_360
    WITH METRICS AS (
        SELECT SK_CUSTOMER,
            COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
            SUM(TOTAL_AMOUNT)               AS TOTAL_REVENUE,
            AVG(TOTAL_AMOUNT)               AS AVG_ORDER_VALUE,
            DATEDIFF('day',MAX(TO_DATE(ORDER_DATE_KEY::VARCHAR,'YYYYMMDD')),CURRENT_DATE()) AS DAYS_SINCE_LAST
        FROM SILVER_DB.FACTS.FACT_ORDERS GROUP BY 1
    ),
    RFM AS (
        SELECT *,
            NTILE(5) OVER (ORDER BY DAYS_SINCE_LAST ASC) +
            NTILE(5) OVER (ORDER BY TOTAL_ORDERS DESC) +
            NTILE(5) OVER (ORDER BY TOTAL_REVENUE DESC) AS RFM_SCORE
        FROM METRICS
    ),
    SCD_COUNTS AS (
        -- Count how many times segment/loyalty changed per customer
        SELECT CUSTOMER_ID,
            COUNT(*) - 1                                                              AS SEGMENT_CHANGES,
            COUNT(DISTINCT LOYALTY_TIER) - 1                                          AS LOYALTY_CHANGES
        FROM SILVER_DB.DIMENSIONS.DIM_CUSTOMERS
        GROUP BY 1
    )
    SELECT
        c.SK_CUSTOMER, c.CUSTOMER_ID, c.CUSTOMER_NAME, c.EMAIL,
        c.SEGMENT, c.LOYALTY_TIER, c.REGION_ID,
        m.TOTAL_ORDERS, m.TOTAL_REVENUE, m.AVG_ORDER_VALUE, m.DAYS_SINCE_LAST,
        sc.SEGMENT_CHANGES, sc.LOYALTY_CHANGES,
        r.RFM_SCORE,
        CASE WHEN r.RFM_SCORE >= 12 THEN 'Platinum'
             WHEN r.RFM_SCORE >= 9  THEN 'Gold'
             WHEN r.RFM_SCORE >= 6  THEN 'Silver'
             ELSE 'Bronze' END AS CUSTOMER_TIER
    FROM RFM r
    JOIN SILVER_DB.DIMENSIONS.DIM_CUSTOMERS c ON c.SK_CUSTOMER=r.SK_CUSTOMER AND c.IS_CURRENT=TRUE
    LEFT JOIN SCD_COUNTS sc ON sc.CUSTOMER_ID=c.CUSTOMER_ID;

    RETURN OBJECT_CONSTRUCT('status','SUCCESS',
        'duration_sec',DATEDIFF('second',:v_start,CURRENT_TIMESTAMP()));
EXCEPTION WHEN OTHER THEN RETURN OBJECT_CONSTRUCT('status','FAILED','error',SQLERRM);
END;
$$;

-- ─────────────────────────────────────────────────────────────
-- GOLD VIEWS
-- ─────────────────────────────────────────────────────────────
USE SCHEMA REPORTING;

CREATE MATERIALIZED VIEW IF NOT EXISTS MV_DAILY_KPI AS
SELECT
    d.FULL_DATE, d.YEAR, d.MONTH_NAME, d.QUARTER_NAME,
    f.STATUS,
    c.SEGMENT, c.LOYALTY_TIER,
    COUNT(DISTINCT f.ORDER_ID)        ORDERS,
    COUNT(DISTINCT f.SK_CUSTOMER)     CUSTOMERS,
    SUM(f.TOTAL_AMOUNT)               GROSS_REVENUE,
    SUM(f.NET_AMOUNT)                 NET_REVENUE,
    SUM(f.PROFIT)                     PROFIT,
    AVG(f.TOTAL_AMOUNT)               AVG_ORDER_VALUE
FROM SILVER_DB.FACTS.FACT_ORDERS f
JOIN SILVER_DB.DIMENSIONS.DIM_DATE d ON d.DATE_KEY=f.ORDER_DATE_KEY
LEFT JOIN SILVER_DB.DIMENSIONS.DIM_CUSTOMERS c ON c.SK_CUSTOMER=f.SK_CUSTOMER
GROUP BY 1,2,3,4,5,6,7;

CREATE SECURE VIEW IF NOT EXISTS V_SEGMENT_PERFORMANCE AS
SELECT
    d.YEAR, d.QUARTER_NAME, d.MONTH_NAME,
    c.SEGMENT,
    c.LOYALTY_TIER,
    COUNT(DISTINCT f.ORDER_ID)   AS ORDERS,
    SUM(f.NET_AMOUNT)            AS NET_REVENUE,
    AVG(f.NET_AMOUNT)            AS AVG_ORDER_VALUE,
    SUM(f.PROFIT)                AS PROFIT,
    -- Window: running total by segment per year
    SUM(SUM(f.NET_AMOUNT)) OVER (
        PARTITION BY d.YEAR, c.SEGMENT
        ORDER BY d.MONTH_NUM
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS YTD_REVENUE_BY_SEGMENT
FROM SILVER_DB.FACTS.FACT_ORDERS f
JOIN SILVER_DB.DIMENSIONS.DIM_DATE d ON d.DATE_KEY=f.ORDER_DATE_KEY
LEFT JOIN SILVER_DB.DIMENSIONS.DIM_CUSTOMERS c ON c.SK_CUSTOMER=f.SK_CUSTOMER
GROUP BY 1,2,3,4,5;

-- SCD2 Analysis View — show customer journey across segment changes
CREATE SECURE VIEW IF NOT EXISTS V_CUSTOMER_SEGMENT_JOURNEY AS
SELECT
    h.CUSTOMER_ID,
    h.VERSION_NUM,
    h.SEGMENT                   AS SEGMENT_AT_VERSION,
    h.LOYALTY_TIER              AS LOYALTY_AT_VERSION,
    h.PREV_SEGMENT              AS PREV_SEGMENT,     -- Type 3 column
    h.PREV_LOYALTY_TIER         AS PREV_LOYALTY,
    h.EFF_START_DATE,
    h.EFF_END_DATE,
    COALESCE(h.EFF_END_DATE, CURRENT_DATE()) - h.EFF_START_DATE AS DAYS_AT_VERSION,
    h.CDC_OPERATION,
    h.CHANGED_COLS,
    SUM(COALESCE(f.TOTAL_AMOUNT,0)) OVER (
        PARTITION BY h.CUSTOMER_ID, h.SK_CUSTOMER
    ) AS REVENUE_IN_THIS_VERSION  -- how much did customer spend while at this segment
FROM SILVER_DB.DIMENSIONS.DIM_CUSTOMERS h
LEFT JOIN SILVER_DB.FACTS.FACT_ORDERS f
    ON f.SK_CUSTOMER = h.SK_CUSTOMER   -- FK is to the version active at order time
ORDER BY h.CUSTOMER_ID, h.VERSION_NUM;

-- ═══════════════════════════════════════════════════════════════
-- COMPLETE TASK DAG — end to end pipeline
-- ═══════════════════════════════════════════════════════════════
USE ROLE DATA_ENG_ROLE;
USE DATABASE COMMON_DB;
USE SCHEMA UTILITIES;

-- Audit log for pipeline
CREATE TABLE IF NOT EXISTS COMMON_DB.AUDIT.PIPELINE_LOG (
    LOG_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    BATCH_ID    VARCHAR(100),
    TASK_NAME   VARCHAR(100),
    STATUS      VARCHAR(20),
    STARTED_AT  TIMESTAMP_NTZ,
    ENDED_AT    TIMESTAMP_NTZ,
    ROWS_PROC   NUMBER,
    RESULT      VARIANT,
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ── ROOT TASK ────────────────────────────────────────────────
CREATE OR REPLACE TASK TASK_CDC_PIPELINE_ROOT
    WAREHOUSE         = TRANSFORM_WH
    SCHEDULE          = 'USING CRON 0 * * * * UTC'   -- every hour
    ERROR_INTEGRATION = SNS_ALERTS
    USER_TASK_TIMEOUT_MS = 3600000
    COMMENT = 'Root: hourly CDC pipeline — only runs when Bronze streams have data'
    WHEN
        SYSTEM$STREAM_HAS_DATA('CDC_DB.STREAMS.STR_CUSTOMERS') OR
        SYSTEM$STREAM_HAS_DATA('CDC_DB.STREAMS.STR_PRODUCTS')  OR
        SYSTEM$STREAM_HAS_DATA('CDC_DB.STREAMS.STR_ORDERS')    OR
        SYSTEM$STREAM_HAS_DATA('CDC_DB.STREAMS.STR_EMPLOYEES') OR
        SYSTEM$STREAM_HAS_DATA('CDC_DB.STREAMS.STR_STORES')
AS
DECLARE
    batch_id VARCHAR;
BEGIN
    batch_id := 'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS');
    INSERT INTO COMMON_DB.AUDIT.PIPELINE_LOG (BATCH_ID,TASK_NAME,STATUS,STARTED_AT)
    VALUES (:batch_id,'ROOT','RUNNING',CURRENT_TIMESTAMP());
END;

-- ── CDC CLASSIFY TASKS (parallel) ────────────────────────────
CREATE OR REPLACE TASK TASK_CLASSIFY_CUSTOMERS
    WAREHOUSE=TRANSFORM_WH AFTER TASK_CDC_PIPELINE_ROOT
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL CDC_DB.CONTROL.SP_CLASSIFY_CUSTOMER_CHANGES(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

CREATE OR REPLACE TASK TASK_CLASSIFY_PRODUCTS
    WAREHOUSE=TRANSFORM_WH AFTER TASK_CDC_PIPELINE_ROOT
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL CDC_DB.CONTROL.SP_CLASSIFY_CUSTOMER_CHANGES(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

CREATE OR REPLACE TASK TASK_CLASSIFY_EMPLOYEES
    WAREHOUSE=TRANSFORM_WH AFTER TASK_CDC_PIPELINE_ROOT
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL CDC_DB.CONTROL.SP_CLASSIFY_CUSTOMER_CHANGES(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

-- ── SCD2 DIMENSION TASKS (after classify) ────────────────────
CREATE OR REPLACE TASK TASK_SCD2_CUSTOMERS
    WAREHOUSE=TRANSFORM_WH
    AFTER TASK_CLASSIFY_CUSTOMERS, TASK_CLASSIFY_EMPLOYEES
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL SILVER_DB.DIMENSIONS.SP_SCD2_CUSTOMERS(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

CREATE OR REPLACE TASK TASK_SCD2_PRODUCTS
    WAREHOUSE=TRANSFORM_WH
    AFTER TASK_CLASSIFY_PRODUCTS
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL SILVER_DB.DIMENSIONS.SP_SCD2_PRODUCTS(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

CREATE OR REPLACE TASK TASK_SCD1_STORES
    WAREHOUSE=TRANSFORM_WH AFTER TASK_CDC_PIPELINE_ROOT
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL SILVER_DB.DIMENSIONS.SP_SCD1_STORES(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

-- ── FACT LOAD (after ALL dims) ────────────────────────────────
CREATE OR REPLACE TASK TASK_LOAD_FACTS
    WAREHOUSE=TRANSFORM_WH
    AFTER TASK_SCD2_CUSTOMERS, TASK_SCD2_PRODUCTS, TASK_SCD1_STORES
    ERROR_INTEGRATION=SNS_ALERTS
AS
    CALL SILVER_DB.FACTS.SP_LOAD_FACT_ORDERS(
        'BATCH_' || TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS')
    );

-- ── GOLD BUILD (after facts) ──────────────────────────────────
CREATE OR REPLACE TASK TASK_BUILD_DAILY_SUMMARY
    WAREHOUSE=TRANSFORM_WH AFTER TASK_LOAD_FACTS
    ERROR_INTEGRATION=SNS_ALERTS
AS  CALL GOLD_DB.SALES_MART.SP_BUILD_DAILY_SUMMARY();

CREATE OR REPLACE TASK TASK_BUILD_CUSTOMER_360
    WAREHOUSE=TRANSFORM_WH AFTER TASK_LOAD_FACTS
    ERROR_INTEGRATION=SNS_ALERTS
AS  CALL GOLD_DB.CUSTOMER_MART.SP_BUILD_CUSTOMER_360();

-- ── SUCCESS NOTIFICATION ──────────────────────────────────────
CREATE OR REPLACE TASK TASK_PIPELINE_COMPLETE
    WAREHOUSE=TRANSFORM_WH
    AFTER TASK_BUILD_DAILY_SUMMARY, TASK_BUILD_CUSTOMER_360
AS
    INSERT INTO COMMON_DB.AUDIT.PIPELINE_LOG
        (BATCH_ID,TASK_NAME,STATUS,STARTED_AT,ENDED_AT)
    VALUES (
        'BATCH_'||TO_CHAR(CURRENT_TIMESTAMP(),'YYYYMMDD_HH24MISS'),
        'PIPELINE_COMPLETE','SUCCESS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP()
    );

-- ── RESUME ORDER: LEAVES FIRST, ROOT LAST ────────────────────
ALTER TASK TASK_PIPELINE_COMPLETE     RESUME;
ALTER TASK TASK_BUILD_CUSTOMER_360    RESUME;
ALTER TASK TASK_BUILD_DAILY_SUMMARY   RESUME;
ALTER TASK TASK_LOAD_FACTS            RESUME;
ALTER TASK TASK_SCD1_STORES           RESUME;
ALTER TASK TASK_SCD2_PRODUCTS         RESUME;
ALTER TASK TASK_SCD2_CUSTOMERS        RESUME;
ALTER TASK TASK_CLASSIFY_EMPLOYEES    RESUME;
ALTER TASK TASK_CLASSIFY_PRODUCTS     RESUME;
ALTER TASK TASK_CLASSIFY_CUSTOMERS    RESUME;
ALTER TASK TASK_CDC_PIPELINE_ROOT     RESUME;   -- LAST

-- ── PIPELINE MONITORING QUERIES ───────────────────────────────
SELECT NAME, STATE, ERROR_MESSAGE, SCHEDULED_TIME, COMPLETED_TIME,
    DATEDIFF('second',QUERY_START_TIME,COMPLETED_TIME) AS SEC
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour',-24,CURRENT_TIMESTAMP())
))
ORDER BY SCHEDULED_TIME DESC;
