-- ============================================================
-- FILE: 01_setup/02_rbac_roles_grants.sql
-- PURPOSE: Create role hierarchy, grant privileges
-- RUN AS: SECURITYADMIN (for roles) + SYSADMIN (for object grants)
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- ROLE HIERARCHY DIAGRAM
-- ─────────────────────────────────────────────────────────────
--
--   ACCOUNTADMIN
--       │
--   SECURITYADMIN ──── SYSADMIN
--       │                  │
--   USERADMIN         ETL_ADMIN_ROLE
--                          │
--              ┌───────────┼────────────┐
--         DATA_ENGINEER  ANALYST_ROLE  DATA_SCIENTIST_ROLE
--              │              │
--         ETL_ROLE       SENIOR_ANALYST_ROLE
--                             │
--                        JUNIOR_ANALYST_ROLE
--
-- ─────────────────────────────────────────────────────────────

USE ROLE SECURITYADMIN;

-- ─────────────────────────────────────────────────────────────
-- CREATE CUSTOM ROLES
-- ─────────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS ETL_ADMIN_ROLE
    COMMENT = 'Full ETL admin — manage pipelines, stages, tasks';

CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE
    COMMENT = 'Data engineers — create and run ETL in all layers';

CREATE ROLE IF NOT EXISTS ETL_ROLE
    COMMENT = 'ETL service account role — read/write for pipeline execution';

CREATE ROLE IF NOT EXISTS SENIOR_ANALYST_ROLE
    COMMENT = 'Senior analysts — read all Gold + Silver tables';

CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Analysts — read Gold layer (business-ready data only)';

CREATE ROLE IF NOT EXISTS JUNIOR_ANALYST_ROLE
    COMMENT = 'Junior analysts — read specific Gold views with masking';

CREATE ROLE IF NOT EXISTS DATA_SCIENTIST_ROLE
    COMMENT = 'Data scientists — read Silver + Gold, use Snowpark';

CREATE ROLE IF NOT EXISTS REPORT_VIEWER_ROLE
    COMMENT = 'BI tool service account — read Gold reporting views only';

-- ─────────────────────────────────────────────────────────────
-- ROLE HIERARCHY (child → parent inheritance)
-- ─────────────────────────────────────────────────────────────

-- ETL hierarchy
GRANT ROLE ETL_ROLE            TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE DATA_ENGINEER_ROLE  TO ROLE ETL_ADMIN_ROLE;
GRANT ROLE ETL_ADMIN_ROLE      TO ROLE SYSADMIN;

-- Analyst hierarchy
GRANT ROLE JUNIOR_ANALYST_ROLE TO ROLE ANALYST_ROLE;
GRANT ROLE ANALYST_ROLE        TO ROLE SENIOR_ANALYST_ROLE;
GRANT ROLE SENIOR_ANALYST_ROLE TO ROLE DATA_ENGINEER_ROLE;

-- Data science
GRANT ROLE DATA_SCIENTIST_ROLE TO ROLE DATA_ENGINEER_ROLE;

-- Reporting
GRANT ROLE REPORT_VIEWER_ROLE  TO ROLE ANALYST_ROLE;

-- ─────────────────────────────────────────────────────────────
-- WAREHOUSE GRANTS
-- ─────────────────────────────────────────────────────────────

GRANT USAGE ON WAREHOUSE INGESTION_WH   TO ROLE ETL_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH   TO ROLE ETL_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH   TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH   TO ROLE REPORT_VIEWER_ROLE;
GRANT USAGE ON WAREHOUSE DATA_SCIENCE_WH TO ROLE DATA_SCIENTIST_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH          TO ROLE DATA_ENGINEER_ROLE;

-- ─────────────────────────────────────────────────────────────
-- DATABASE & SCHEMA GRANTS
-- ─────────────────────────────────────────────────────────────

-- BRONZE_DB: ETL roles only (analysts never see raw data)
GRANT USAGE ON DATABASE BRONZE_DB TO ROLE ETL_ROLE;
GRANT USAGE ON DATABASE BRONZE_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BRONZE_DB TO ROLE ETL_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BRONZE_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE BRONZE_DB TO ROLE ETL_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BRONZE_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE BRONZE_DB TO ROLE ETL_ROLE;
GRANT ALL   ON FUTURE TABLES IN DATABASE BRONZE_DB TO ROLE DATA_ENGINEER_ROLE;

-- SILVER_DB: ETL write, data scientists and senior analysts read
GRANT USAGE ON DATABASE SILVER_DB TO ROLE ETL_ROLE;
GRANT USAGE ON DATABASE SILVER_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE SILVER_DB TO ROLE SENIOR_ANALYST_ROLE;
GRANT USAGE ON DATABASE SILVER_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE ETL_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE SENIOR_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE SILVER_DB TO ROLE SENIOR_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE SILVER_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE SILVER_DB TO ROLE ETL_ROLE;
GRANT ALL   ON ALL TABLES IN DATABASE SILVER_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SILVER_DB TO ROLE SENIOR_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SILVER_DB TO ROLE DATA_SCIENTIST_ROLE;
GRANT ALL   ON FUTURE TABLES IN DATABASE SILVER_DB TO ROLE DATA_ENGINEER_ROLE;

-- GOLD_DB: All analysts read, ETL writes
GRANT USAGE ON DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE GOLD_DB TO ROLE REPORT_VIEWER_ROLE;
GRANT USAGE ON DATABASE GOLD_DB TO ROLE ETL_ROLE;
GRANT USAGE ON DATABASE GOLD_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE REPORT_VIEWER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE ETL_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS  IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS  IN DATABASE GOLD_DB TO ROLE REPORT_VIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT ALL   ON ALL TABLES  IN DATABASE GOLD_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE GOLD_DB TO ROLE REPORT_VIEWER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT ALL   ON FUTURE TABLES  IN DATABASE GOLD_DB TO ROLE DATA_ENGINEER_ROLE;

-- COMMON_DB: Stages, file formats
GRANT USAGE ON DATABASE COMMON_DB TO ROLE ETL_ROLE;
GRANT USAGE ON DATABASE COMMON_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE COMMON_DB TO ROLE ETL_ROLE;
GRANT ALL   ON ALL SCHEMAS IN DATABASE COMMON_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT ALL   ON ALL STAGES  IN DATABASE COMMON_DB TO ROLE ETL_ROLE;
GRANT ALL   ON ALL STAGES  IN DATABASE COMMON_DB TO ROLE DATA_ENGINEER_ROLE;

-- ─────────────────────────────────────────────────────────────
-- CREATE SAMPLE USERS (adjust passwords in production)
-- ─────────────────────────────────────────────────────────────

USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS ETL_SERVICE_ACCOUNT
    PASSWORD            = 'ETL_Serv!ce_2024'
    DEFAULT_ROLE        = ETL_ROLE
    DEFAULT_WAREHOUSE   = INGESTION_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT             = 'Service account for ETL pipeline execution';

CREATE USER IF NOT EXISTS ALICE_ENGINEER
    PASSWORD            = 'Alice_Eng!2024'
    DEFAULT_ROLE        = DATA_ENGINEER_ROLE
    DEFAULT_WAREHOUSE   = TRANSFORM_WH
    COMMENT             = 'Data engineer Alice';

CREATE USER IF NOT EXISTS BOB_ANALYST
    PASSWORD            = 'Bob_Ana!2024'
    DEFAULT_ROLE        = ANALYST_ROLE
    DEFAULT_WAREHOUSE   = ANALYTICS_WH
    COMMENT             = 'Business analyst Bob';

CREATE USER IF NOT EXISTS CAROL_SCIENTIST
    PASSWORD            = 'Carol_Sci!2024'
    DEFAULT_ROLE        = DATA_SCIENTIST_ROLE
    DEFAULT_WAREHOUSE   = DATA_SCIENCE_WH
    COMMENT             = 'Data scientist Carol';

-- Assign roles to users
GRANT ROLE ETL_ROLE             TO USER ETL_SERVICE_ACCOUNT;
GRANT ROLE DATA_ENGINEER_ROLE   TO USER ALICE_ENGINEER;
GRANT ROLE ANALYST_ROLE         TO USER BOB_ANALYST;
GRANT ROLE DATA_SCIENTIST_ROLE  TO USER CAROL_SCIENTIST;

-- Verify
SHOW ROLES;
SHOW GRANTS TO ROLE ANALYST_ROLE;
