-- ============================================================
-- FILE: 07_monitoring/01_resource_monitors_alerts.sql
-- PURPOSE: Resource monitors, cost tracking, ACCOUNT_USAGE monitoring
-- RUN AS: ACCOUNTADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ─────────────────────────────────────────────────────────────
-- SECTION A: RESOURCE MONITORS
-- ─────────────────────────────────────────────────────────────

-- Account-level monthly cap (hard ceiling)
CREATE RESOURCE MONITOR IF NOT EXISTS RM_ACCOUNT_MONTHLY
    CREDIT_QUOTA    = 5000
    FREQUENCY       = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    NOTIFY_USERS    = ('ALICE_ENGINEER')
    TRIGGERS
        ON 50  PERCENT DO NOTIFY
        ON 75  PERCENT DO NOTIFY
        ON 90  PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND            -- suspend all warehouses
        ON 115 PERCENT DO SUSPEND_IMMEDIATE  -- kill running queries
    COMMENT = 'Account-level monthly credit cap — 5000 credits';

ALTER ACCOUNT SET RESOURCE_MONITOR = RM_ACCOUNT_MONTHLY;

-- Per-warehouse monitors for team cost attribution
CREATE RESOURCE MONITOR IF NOT EXISTS RM_ANALYTICS_MONTHLY
    CREDIT_QUOTA = 1500
    FREQUENCY    = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80  PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_TRANSFORM_MONTHLY
    CREDIT_QUOTA = 2000
    FREQUENCY    = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80  PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE RESOURCE MONITOR IF NOT EXISTS RM_DEV_WEEKLY
    CREDIT_QUOTA = 50
    FREQUENCY    = WEEKLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 90  PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE ANALYTICS_WH   SET RESOURCE_MONITOR = RM_ANALYTICS_MONTHLY;
ALTER WAREHOUSE TRANSFORM_WH   SET RESOURCE_MONITOR = RM_TRANSFORM_MONTHLY;
ALTER WAREHOUSE DEV_WH         SET RESOURCE_MONITOR = RM_DEV_WEEKLY;

-- ─────────────────────────────────────────────────────────────
-- SECTION B: AUDIT LOG TABLE
-- ─────────────────────────────────────────────────────────────

USE ROLE DATA_ENGINEER_ROLE;

CREATE TABLE IF NOT EXISTS COMMON_DB.AUDIT.PIPELINE_RUN_LOG (
    LOG_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    RUN_ID          VARCHAR(100),          -- UUID per pipeline run
    STAGE           VARCHAR(100),          -- which step
    STATUS          VARCHAR(20),           -- RUNNING|SUCCESS|FAILED|SKIPPED
    STARTED_AT      TIMESTAMP_NTZ,
    COMPLETED_AT    TIMESTAMP_NTZ,
    ROW_COUNT       NUMBER,
    ERROR_MESSAGE   VARCHAR(5000),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS COMMON_DB.AUDIT.DATA_QUALITY_LOG (
    LOG_ID          NUMBER AUTOINCREMENT PRIMARY KEY,
    CHECK_DATE      DATE DEFAULT CURRENT_DATE(),
    TABLE_NAME      VARCHAR(200),
    CHECK_NAME      VARCHAR(200),
    CHECK_TYPE      VARCHAR(50),    -- NULL_CHECK|RANGE|UNIQUENESS|REFERENTIAL
    ROWS_CHECKED    NUMBER,
    ROWS_FAILED     NUMBER,
    PASS_RATE_PCT   NUMBER(6,2),
    STATUS          VARCHAR(10),    -- PASS|WARN|FAIL
    DETAILS         VARIANT,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ─────────────────────────────────────────────────────────────
-- SECTION C: MONITORING QUERIES (run regularly / on dashboard)
-- ─────────────────────────────────────────────────────────────

-- Daily credit usage (last 30 days)
SELECT
    USAGE_DATE,
    SUM(CREDITS_USED_COMPUTE)         AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES)  AS CLOUD_SVCCS_CREDITS,
    SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE USAGE_DATE >= DATEADD('day', -30, CURRENT_DATE())
GROUP BY 1
ORDER BY 1 DESC;

-- Credit spend by warehouse (current month)
SELECT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED)               AS TOTAL_CREDITS,
    SUM(CREDITS_USED_COMPUTE)       AS COMPUTE_CREDITS,
    COUNT(DISTINCT DATE(START_TIME)) AS ACTIVE_DAYS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATE_TRUNC('month', CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 2 DESC;

-- Top 10 most expensive queries (last 7 days)
SELECT
    USER_NAME,
    WAREHOUSE_NAME,
    ROUND(TOTAL_ELAPSED_TIME / 1000, 1)     AS DURATION_SEC,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROUND(PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL,0) * 100, 1) AS PCT_SCANNED,
    ROUND(BYTES_SPILLED_TO_REMOTE_STORAGE / 1e9, 2) AS REMOTE_SPILL_GB,
    LEFT(QUERY_TEXT, 200)                   AS QUERY_PREVIEW
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND TOTAL_ELAPSED_TIME > 30000           -- only queries > 30 seconds
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 10;

-- Warehouses with poor auto-suspend (running but idle)
SELECT
    W.WAREHOUSE_NAME,
    SUM(W.CREDITS_USED)             AS CREDITS_USED,
    COUNT(Q.QUERY_ID)               AS QUERY_COUNT,
    ROUND(SUM(W.CREDITS_USED) / NULLIF(COUNT(Q.QUERY_ID),0), 4) AS CREDITS_PER_QUERY
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY W
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY Q
    ON  Q.WAREHOUSE_NAME = W.WAREHOUSE_NAME
    AND Q.START_TIME BETWEEN W.START_TIME AND W.END_TIME
WHERE W.START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY 1
HAVING COUNT(Q.QUERY_ID) = 0 OR CREDITS_PER_QUERY > 1.0
ORDER BY CREDITS_USED DESC;

-- Login failures (security monitoring)
SELECT
    USER_NAME,
    CLIENT_IP,
    ERROR_CODE,
    ERROR_MESSAGE,
    EVENT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO'
  AND EVENT_TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC
LIMIT 50;

-- Data access audit (who queried sensitive tables)
SELECT
    USER_NAME,
    QUERY_START_TIME,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())
  AND EXISTS (
    SELECT 1
    FROM TABLE(FLATTEN(BASE_OBJECTS_ACCESSED)) f
    WHERE f.value:objectName::VARCHAR ILIKE '%DIM_CUSTOMERS%'
  )
ORDER BY QUERY_START_TIME DESC;

-- Storage usage by layer
SELECT
    TABLE_CATALOG                               AS DATABASE_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    ROUND(ACTIVE_BYTES / 1e9, 3)               AS ACTIVE_GB,
    ROUND(TIME_TRAVEL_BYTES / 1e9, 3)          AS TIME_TRAVEL_GB,
    ROUND(FAILSAFE_BYTES / 1e9, 3)             AS FAILSAFE_GB,
    ROUND((ACTIVE_BYTES + TIME_TRAVEL_BYTES + FAILSAFE_BYTES) / 1e9, 3) AS TOTAL_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE DELETED = FALSE
ORDER BY TOTAL_GB DESC
LIMIT 20;

-- Pipeline health check (last 24 hours)
SELECT
    STAGE,
    STATUS,
    COUNT(*)                                        AS RUN_COUNT,
    AVG(DATEDIFF('second', STARTED_AT, COMPLETED_AT)) AS AVG_DURATION_SEC,
    MAX(DATEDIFF('second', STARTED_AT, COMPLETED_AT)) AS MAX_DURATION_SEC
FROM COMMON_DB.AUDIT.PIPELINE_RUN_LOG
WHERE CREATED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
GROUP BY 1, 2
ORDER BY 1, 2;
