-- ============================================================
-- FILE: 01_setup/01_setup_all.sql
-- PROJECT: Retail CDC & SCD Pipeline — Complete Setup
-- COVERS: Databases, Warehouses, Roles, S3 Integration, Stages
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- DATABASES
-- ─────────────────────────────────────────────────────────────
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BRONZE_DB  DATA_RETENTION_TIME_IN_DAYS = 1  COMMENT = 'Raw landing — transient, source-exact';
CREATE DATABASE IF NOT EXISTS SILVER_DB  DATA_RETENTION_TIME_IN_DAYS = 30 COMMENT = 'Cleansed SCD dims + conformed facts';
CREATE DATABASE IF NOT EXISTS GOLD_DB    DATA_RETENTION_TIME_IN_DAYS = 14 COMMENT = 'Business aggregations and marts';
CREATE DATABASE IF NOT EXISTS COMMON_DB  DATA_RETENTION_TIME_IN_DAYS = 7  COMMENT = 'Shared: stages, formats, utilities, audit';
CREATE DATABASE IF NOT EXISTS CDC_DB     DATA_RETENTION_TIME_IN_DAYS = 7  COMMENT = 'CDC engine: streams, staging, control tables';

-- SCHEMAS
CREATE SCHEMA IF NOT EXISTS BRONZE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS BRONZE_DB.ARCHIVE;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.DIMENSIONS;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.FACTS;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS GOLD_DB.SALES_MART;
CREATE SCHEMA IF NOT EXISTS GOLD_DB.CUSTOMER_MART;
CREATE SCHEMA IF NOT EXISTS GOLD_DB.REPORTING;
CREATE SCHEMA IF NOT EXISTS COMMON_DB.INGESTION;
CREATE SCHEMA IF NOT EXISTS COMMON_DB.UTILITIES;
CREATE SCHEMA IF NOT EXISTS COMMON_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS CDC_DB.STREAMS;
CREATE SCHEMA IF NOT EXISTS CDC_DB.CONTROL;
CREATE SCHEMA IF NOT EXISTS CDC_DB.STAGING;

-- ─────────────────────────────────────────────────────────────
-- WAREHOUSES
-- ─────────────────────────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS INGEST_WH
    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60  AUTO_RESUME=TRUE COMMENT='COPY INTO / Snowpipe';
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=120 AUTO_RESUME=TRUE COMMENT='CDC + SCD transforms';
CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH
    WAREHOUSE_SIZE='MEDIUM' MIN_CLUSTER_COUNT=1 MAX_CLUSTER_COUNT=3
    AUTO_SUSPEND=180 AUTO_RESUME=TRUE COMMENT='BI queries — multi-cluster';
CREATE WAREHOUSE IF NOT EXISTS DEV_WH
    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=30  AUTO_RESUME=TRUE COMMENT='Developer sandbox';

-- ─────────────────────────────────────────────────────────────
-- ROLES & RBAC
-- ─────────────────────────────────────────────────────────────
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ETL_ADMIN_ROLE  COMMENT='Full ETL admin';
CREATE ROLE IF NOT EXISTS DATA_ENG_ROLE   COMMENT='Data engineers';
CREATE ROLE IF NOT EXISTS ETL_SVC_ROLE    COMMENT='Pipeline service account';
CREATE ROLE IF NOT EXISTS ANALYST_ROLE    COMMENT='Business analysts — Gold only';
CREATE ROLE IF NOT EXISTS SR_ANALYST_ROLE COMMENT='Senior analysts — Silver + Gold';
CREATE ROLE IF NOT EXISTS CDC_SVC_ROLE    COMMENT='CDC engine service account';

GRANT ROLE ETL_SVC_ROLE   TO ROLE DATA_ENG_ROLE;
GRANT ROLE DATA_ENG_ROLE  TO ROLE ETL_ADMIN_ROLE;
GRANT ROLE CDC_SVC_ROLE   TO ROLE DATA_ENG_ROLE;
GRANT ROLE ANALYST_ROLE   TO ROLE SR_ANALYST_ROLE;
GRANT ROLE SR_ANALYST_ROLE TO ROLE DATA_ENG_ROLE;
GRANT ROLE ETL_ADMIN_ROLE TO ROLE SYSADMIN;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE INGEST_WH    TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE CDC_SVC_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH       TO ROLE DATA_ENG_ROLE;

-- DB grants — BRONZE (ETL only)
GRANT USAGE ON DATABASE BRONZE_DB TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON DATABASE BRONZE_DB TO ROLE CDC_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BRONZE_DB TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BRONZE_DB TO ROLE CDC_SVC_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN DATABASE BRONZE_DB TO ROLE ETL_SVC_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE BRONZE_DB TO ROLE CDC_SVC_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE BRONZE_DB TO ROLE ETL_SVC_ROLE;

-- DB grants — CDC_DB
GRANT USAGE ON DATABASE CDC_DB TO ROLE CDC_SVC_ROLE;
GRANT USAGE ON DATABASE CDC_DB TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CDC_DB TO ROLE CDC_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CDC_DB TO ROLE ETL_SVC_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE CDC_DB TO ROLE CDC_SVC_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE CDC_DB TO ROLE CDC_SVC_ROLE;

-- DB grants — SILVER
GRANT USAGE ON DATABASE SILVER_DB TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON DATABASE SILVER_DB TO ROLE CDC_SVC_ROLE;
GRANT USAGE ON DATABASE SILVER_DB TO ROLE SR_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE CDC_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE SR_ANALYST_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE SILVER_DB TO ROLE ETL_SVC_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE SILVER_DB TO ROLE CDC_SVC_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE SILVER_DB TO ROLE SR_ANALYST_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE SILVER_DB TO ROLE ETL_SVC_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE SILVER_DB TO ROLE CDC_SVC_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SILVER_DB TO ROLE SR_ANALYST_ROLE;

-- DB grants — GOLD
GRANT USAGE ON DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE GOLD_DB TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE ETL_SVC_ROLE;
GRANT SELECT ON ALL TABLES  IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS   IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE GOLD_DB TO ROLE ETL_SVC_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE GOLD_DB TO ROLE ANALYST_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE GOLD_DB TO ROLE ETL_SVC_ROLE;

-- ─────────────────────────────────────────────────────────────
-- S3 STORAGE INTEGRATION
-- ─────────────────────────────────────────────────────────────
USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION IF NOT EXISTS S3_RETAIL_INT
    TYPE                      = EXTERNAL_STAGE
    STORAGE_PROVIDER          = 'S3'
    ENABLED                   = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://retail-cdc-bucket/');

-- Run DESC to get IAM ARN → add to AWS bucket trust policy
DESC INTEGRATION S3_RETAIL_INT;

GRANT USAGE ON INTEGRATION S3_RETAIL_INT TO ROLE ETL_SVC_ROLE;
GRANT USAGE ON INTEGRATION S3_RETAIL_INT TO ROLE DATA_ENG_ROLE;

-- SNS for task failure alerts
CREATE NOTIFICATION INTEGRATION IF NOT EXISTS SNS_ALERTS
    TYPE                  = QUEUE
    NOTIFICATION_PROVIDER = AWS_SNS
    ENABLED               = TRUE
    AWS_SNS_TOPIC_ARN     = 'arn:aws:sns:us-east-1:123456789012:retail-cdc-alerts'
    AWS_SNS_ROLE_ARN      = 'arn:aws:iam::123456789012:role/SnowflakeSNSRole';

GRANT USAGE ON INTEGRATION SNS_ALERTS TO ROLE ETL_SVC_ROLE;

-- ─────────────────────────────────────────────────────────────
-- FILE FORMATS
-- ─────────────────────────────────────────────────────────────
USE ROLE SYSADMIN;
USE DATABASE COMMON_DB;
USE SCHEMA INGESTION;

CREATE FILE FORMAT IF NOT EXISTS CSV_FMT
    TYPE='CSV' FIELD_DELIMITER=',' SKIP_HEADER=1
    NULL_IF=('NULL','null','\\N','') EMPTY_FIELD_AS_NULL=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"' TRIM_SPACE=TRUE
    DATE_FORMAT='YYYY-MM-DD' TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS'
    COMPRESSION=AUTO;

CREATE FILE FORMAT IF NOT EXISTS JSON_FMT
    TYPE='JSON' STRIP_OUTER_ARRAY=TRUE COMPRESSION=AUTO;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FMT
    TYPE='PARQUET' SNAPPY_COMPRESSION=TRUE;

-- ─────────────────────────────────────────────────────────────
-- EXTERNAL STAGES
-- ─────────────────────────────────────────────────────────────
CREATE STAGE IF NOT EXISTS STG_S3_CUSTOMERS
    URL='s3://retail-cdc-bucket/raw/customers/'
    STORAGE_INTEGRATION=S3_RETAIL_INT FILE_FORMAT=(FORMAT_NAME='CSV_FMT');

CREATE STAGE IF NOT EXISTS STG_S3_ORDERS
    URL='s3://retail-cdc-bucket/raw/orders/'
    STORAGE_INTEGRATION=S3_RETAIL_INT FILE_FORMAT=(FORMAT_NAME='CSV_FMT');

CREATE STAGE IF NOT EXISTS STG_S3_PRODUCTS
    URL='s3://retail-cdc-bucket/raw/products/'
    STORAGE_INTEGRATION=S3_RETAIL_INT FILE_FORMAT=(FORMAT_NAME='CSV_FMT');

CREATE STAGE IF NOT EXISTS STG_S3_ORDER_ITEMS
    URL='s3://retail-cdc-bucket/raw/order_items/'
    STORAGE_INTEGRATION=S3_RETAIL_INT FILE_FORMAT=(FORMAT_NAME='CSV_FMT');

CREATE STAGE IF NOT EXISTS STG_S3_EMPLOYEES
    URL='s3://retail-cdc-bucket/raw/employees/'
    STORAGE_INTEGRATION=S3_RETAIL_INT FILE_FORMAT=(FORMAT_NAME='CSV_FMT');

CREATE STAGE IF NOT EXISTS STG_S3_STORES
    URL='s3://retail-cdc-bucket/raw/stores/'
    STORAGE_INTEGRATION=S3_RETAIL_INT FILE_FORMAT=(FORMAT_NAME='CSV_FMT');

-- ─────────────────────────────────────────────────────────────
-- SEQUENCES for surrogate keys
-- ─────────────────────────────────────────────────────────────
USE SCHEMA COMMON_DB.UTILITIES;

CREATE SEQUENCE IF NOT EXISTS SEQ_CUSTOMER_SK  START=1 INCREMENT=1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PRODUCT_SK   START=1 INCREMENT=1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EMPLOYEE_SK  START=1 INCREMENT=1;
CREATE SEQUENCE IF NOT EXISTS SEQ_STORE_SK     START=1 INCREMENT=1;
CREATE SEQUENCE IF NOT EXISTS SEQ_REGION_SK    START=1 INCREMENT=1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ORDER_SK     START=1 INCREMENT=1;
